### PR TITLE
Increment dev version

### PR DESCRIPTION
**Pull request by jspellman814**

### CODE REVIEW

**Review by jazzsequence — APPROVED** [review]
LGTM but a general question:

What defines a release? At what point does it bump from `0.2.x` to `0.3` or `1.0`?

I think as long as we're pre-AR/pre-GA, it will always be `0.x` (the `1.0` would be when it's officially released to the world), but I also feel like the `0.2` distinction is somewhat arbitrary and not based on any significant features added as compared to `0.1`.

I'm also wondering how we version the SDKs as well. A pattern that we used on Altis was that whenever there was a new Altis version, all of the component modules of Altis were versioned to the same major release (e.g. Altis v7 includes Altis Privacy v7, etc). If changes were made to those modules, they would go into patch releases (e.g. Altis Privacy `7.0.1`) and I think we could maybe use a similar model here, but open to suggestions (and maybe worth chatting with @robloach and the wider team). This is definitely a discussion that is far outside the scope of this PR 😅 but I wanted to throw it out there to start thinking about.

**Comment by RobLoach** [comment]
I'd advocate for semantic versioning https://semver.org/

**Comment by jspellman814** [comment]
Agreed on [semantic versioning](https://semver.org). At this point I think any bug fix or functional change is a release, just because the plugin is in active development. After GA releases will be a little more planned, I imagine.

Trying to remember what got us from 0.1.0 to 0.2.0 and thinking it was the release process implementation... since then I could see the argument that a few things have been minor improvements vs patches, but pre-GA I've personally been a little more lax on following semver. 

I've also been wondering if we'd want to clean up the tags/releases before GA and start clean with a 1.0 (e.g. remove everything prior to 1.0 to avoid potential confusion). If not we'll at least want to go back and mark everything `pre-release`.

The model you mentioned for versioning the SDK sounds good to me, and agreed - we should have a larger discussion. I'll create a card with this info and we can discuss further with all parties.

**Comment by jazzsequence** [comment]
Yeah, I definitely think we should be using SemVer as a guide, but I agree that I think we've added things that would/should be considered "minor versions" that have been tagged in patch releases. Just wanted to put that thought out into the world and get everyone's input on it. Thanks @RobLoach for the link! I definitely know/understand SemVer conceptually, but I don't know that I've ever actually looked at the specifics!

**Comment by jazzsequence** [comment]
@jspellman814 Sidenote, related to the above:

Should we change our default version bump (e.g. PRs like this one)? Or just update to whatever the "correct" version would be when we're ready to cut a release?

**Pull request merged**
