### PR TITLE
[EI-60] Alter actions for new release process

### PR DESCRIPTION
**Pull request by jspellman814**
With these updates, `main` essentially becomes a stable development branch. Once a PR is made against `build` the new action, `build.yml`, will compile assets and make a commit to the PR.

The release workflow would be similar to the following:

1. Create a pull request with production-ready code from `main` against `build`.
2. After automation makes the commit containing the build files, merge the PR into `build`.
3. Locally checkout the `build` branch and pull the latest.
4. Create a new tag: `git tag major.minor.patch`
5. Push the tag to the repo: `git push origin tag major.minor.patch`. This step triggers `release.yml` which will create a new release containing the compiled source.
6. Update `main` version to `major.minor.patch-dev`.

Future development work should always be done off the `main` branch, and PRs should be opened against `main`.

### CODE REVIEW

**Review by jazzsequence — CHANGES_REQUESTED** [review]
This all looks great! Can you add the release workflow into the README?

**Comment by jazzsequence** [comment]
Update to run `composer install` so the release zip file has the global library.

**Review by jazzsequence — APPROVED** [review]
:shipit:

**Comment by jspellman814** [comment]
Will merge and confirm functionality first thing tomorrow.

**Pull request merged**
